//Action Types
export const SET_NFT_CREATE_PREVIEW = 'SET_NFT_CREATE_PREVIEW';
export const CLEAR_NFT_CREATE_PREVIEW = 'CLEAR_NFT_CREATE_PREVIEW';

export const SET_NFT_CREATE_NAME = 'SET_NFT_CREATE_NAME';
export const CLEAR_NFT_CREATE_NAME = 'CLEAR_NFT_CREATE_NAME';

export const SET_NFT_CREATE_EXTERNAL_LINK = 'SET_NFT_CREATE_EXTERNAL_LINK';
export const CLEAR_NFT_CREATE_EXTERNAL_LINK = 'CLEAR_NFT_CREATE_EXTERNAL_LINK';

export const SET_NFT_CREATE_LICENCE_TYPE = 'SET_NFT_CREATE_LICENCE_TYPE';
export const CLEAR_NFT_CREATE_LICENCE_TYPE = 'CLEAR_NFT_CREATE_LICENCE_TYPE';

export const SET_NFT_CREATE_COPIES = 'SET_NFT_CREATE_COPIES';
export const CLEAR_NFT_CREATE_COPIES = 'CLEAR_NFT_CREATE_COPIES';

export const SET_NFT_CREATE_FILE = 'SET_NFT_CREATE_FILE';
export const CLEAR_NFT_CREATE_FILE = 'CLEAR_NFT_CREATE_FILE';

export const SET_NFT_CREATE_CATEGORY = 'SET_NFT_CREATE_CATEGORY';
export const CLEAR_NFT_CREATE_CATEGORY = 'CLEAR_NFT_CREATE_CATEGORY';

export const SET_NFT_CREATE_DESCRIPTION = 'SET_NFT_CREATE_DESCRIPTION';
export const CLEAR_NFT_CREATE_DESCRIPTION = 'CLEAR_NFT_CREATE_DESCRIPTION';

export const SET_NFT_CREATE_COLLECTION = 'SET_NFT_CREATE_COLLECTION';
export const CLEAR_NFT_CREATE_COLLECTION = 'CLEAR_NFT_CREATE_COLLECTION';

export const SET_NFT_CREATE_BLOCKCHAIN = 'SET_NFT_CREATE_BLOCKCHAIN';
export const CLEAR_NFT_CREATE_BLOCKCHAIN = 'CLEAR_NFT_CREATE_BLOCKCHAIN';

export const SET_NFT_CREATE_SALE_TYPE = 'SET_NFT_CREATE_SALE_TYPE';
export const CLEAR_NFT_CREATE_SALE_TYPE = 'CLEAR_NFT_CREATE_SALE_TYPE';

export const SET_NFT_CREATE_PRICE = 'SET_NFT_CREATE_PRICE';
export const CLEAR_NFT_CREATE_PRICE = 'CLEAR_NFT_CREATE_PRICE';

export const SET_NFT_CREATE_AUCTION_START = 'SET_NFT_CREATE_AUCTION_START';
export const CLEAR_NFT_CREATE_AUCTION_START = 'CLEAR_NFT_CREATE_AUCTION_START';

export const SET_NFT_CREATE_AUCTION_END = 'SET_NFT_CREATE_AUCTION_END';
export const CLEAR_NFT_CREATE_AUCTION_END = 'CLEAR_NFT_CREATE_AUCTION_END';

export const SET_NFT_CREATE_CHARITY = 'SET_NFT_CREATE_CHARITY';
export const CLEAR_NFT_CREATE_CHARITY = 'CLEAR_NFT_CREATE_CHARITY';

export const SET_NFT_CREATE_CHARITY_WALLET = 'SET_NFT_CREATE_CHARITY_WALLET';
export const CLEAR_NFT_CREATE_CHARITY_WALLET =
  'CLEAR_NFT_CREATE_CHARITY_WALLET';

export const SET_NFT_CREATE_ROYALTY = 'SET_NFT_CREATE_ROYALTY';
export const CLEAR_NFT_CREATE_ROYALTY = 'CLEAR_NFT_CREATE_ROYALTY';

export const CLEAR_NFT_CREATE_ALL = 'CLEAR_NFT_CREATE_ALL';
